### ISSUE TITLE
Get Images to Work

### ISSUE THREAD

**Issue by DW-87** [CloudBop/dwcr-support#3]
Need to find out why images are not working?

**Comment by CloudBop** [comment]
Now have example loading static images. see front-page/content-hero.php

``` style="background-image: url('../wp-content/themes/pnhuk-theme/assets/src/img/theme/image/mbr.jpg');" ``` 

or 

``` <img src="<?php bloginfo('stylesheet_directory')?>/assets/src/img/theme/image/mbr.jpg"> ```

TODO dynamically add via WP admin
